// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare adapter at build time.
import { default as nextHandler } from "./.open-next/worker.js";
import { rebuildLatestRecommendationSnapshots } from "./lib/meta-beta/aggregation";
import type { D1DatabaseBinding } from "./lib/meta-beta/auth";

interface WorkerEnv {
  DB?: D1DatabaseBinding;
}

interface ScheduledEventLike {
  cron: string;
  scheduledTime: number;
}

interface ExecutionContextLike {
  waitUntil(promise: Promise<unknown>): void;
}

async function cleanupOldUsage(db: D1DatabaseBinding): Promise<void> {
  const cutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  await db.prepare("DELETE FROM ai_usage_daily WHERE usage_date < ?").bind(cutoff).run();
}

export default {
  fetch: nextHandler.fetch,

  async scheduled(
    event: ScheduledEventLike,
    env: WorkerEnv,
    context: ExecutionContextLike,
  ): Promise<void> {
    if (!env.DB) {
      console.warn("Scheduled meta aggregation skipped because the DB binding is unavailable");
      return;
    }

    if (event.cron !== "0 19 * * *") return;
    const scheduledTime = Number.isFinite(event.scheduledTime) ? event.scheduledTime : Date.now();
    const rebuild = rebuildLatestRecommendationSnapshots(env.DB, "jp", scheduledTime);
    context.waitUntil(cleanupOldUsage(env.DB));
    const result = await rebuild;
    console.log("Ranked meta recommendation snapshot rebuilt", result);
  },
};

// Re-export OpenNext durable objects when the generated worker provides them.
// @ts-ignore `.open-next/worker.js` is generated at build time.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
