// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the generated module may already exist locally.
// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare adapter at build time.
import { default as nextHandler } from "./.open-next/worker.js";
import { rebuildLatestRecommendationSnapshots } from "./lib/meta-beta/aggregation";
import type { D1DatabaseBinding } from "./lib/meta-beta/auth";
import { GLOBAL_META_REGION } from "./lib/meta-beta/global-ingest";
import {
  collectRiotRecentCompetitiveMatches,
  type RiotRecentRoute,
} from "./lib/meta-beta/riot-global-collector";
import { RiotValorantApiClient } from "./lib/meta-beta/riot-client";

interface WorkerEnv {
  DB?: D1DatabaseBinding;
  RIOT_API_KEY?: string;
  RIOT_MATCH_DETAIL_BUDGET?: string;
}

interface ScheduledEventLike {
  cron: string;
  scheduledTime: number;
}

interface ExecutionContextLike {
  waitUntil(promise: Promise<unknown>): void;
}

async function cleanupOperationalData(db: D1DatabaseBinding, now = Date.now()): Promise<void> {
  const cutoff = new Date(now - 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  await db.batch([
    db.prepare("DELETE FROM ai_usage_daily WHERE usage_date < ?").bind(cutoff),
    db.prepare("DELETE FROM ai_response_cache WHERE expires_at <= ?").bind(Math.floor(now / 1000)),
  ]);
}

function detailBudget(value: string | undefined): number {
  const parsed = Number.parseInt(value ?? "", 10);
  if (!Number.isFinite(parsed)) return 120;
  return Math.min(Math.max(parsed, 1), 250);
}

function riotClientFactory(apiKey: string): (route: RiotRecentRoute) => RiotValorantApiClient {
  const clients = new Map<RiotRecentRoute, RiotValorantApiClient>();
  return (route) => {
    const existing = clients.get(route);
    if (existing) return existing;
    const client = new RiotValorantApiClient({
      apiKey,
      baseUrl: `https://${route}.api.riotgames.com`,
    });
    clients.set(route, client);
    return client;
  };
}

const worker = {
  fetch: nextHandler.fetch,

  async scheduled(
    event: ScheduledEventLike,
    env: WorkerEnv,
    context: ExecutionContextLike,
  ): Promise<void> {
    if (!env.DB) {
      console.warn("Scheduled ranked-meta task skipped because the DB binding is unavailable");
      return;
    }

    const scheduledTime = Number.isFinite(event.scheduledTime) ? event.scheduledTime : Date.now();

    if (event.cron === "*/10 * * * *") {
      const apiKey = env.RIOT_API_KEY?.trim();
      if (!apiKey) {
        console.warn("Riot recent-match collection skipped because RIOT_API_KEY is missing");
        return;
      }
      const result = await collectRiotRecentCompetitiveMatches(
        env.DB,
        riotClientFactory(apiKey),
        scheduledTime,
        { maximumDetailsPerRun: detailBudget(env.RIOT_MATCH_DETAIL_BUDGET) },
      );
      console.log("Global Riot recent-match collection finished", result);
      return;
    }

    if (event.cron === "0 19 * * *") {
      const rebuild = rebuildLatestRecommendationSnapshots(env.DB, GLOBAL_META_REGION, scheduledTime);
      context.waitUntil(cleanupOperationalData(env.DB, scheduledTime));
      const result = await rebuild;
      console.log("Global ranked meta recommendation snapshot rebuilt", result);
    }
  },
};

export default worker;

// Re-export OpenNext durable objects when the generated worker provides them.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the generated module may already exist locally.
// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare adapter at build time.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
