// @ts-expect-error `.open-next/worker.js` is generated by the Cloudflare adapter at build time.
import { default as nextHandler } from "./.open-next/worker.js";
import { rebuildLatestRecommendationSnapshots } from "./lib/meta-beta/aggregation";
import type { D1DatabaseBinding } from "./lib/meta-beta/auth";
import { collectOptInMatches } from "./lib/meta-beta/collection";
import { RiotValorantApiClient } from "./lib/meta-beta/riot-client";

interface WorkerEnv {
  DB?: D1DatabaseBinding;
  RIOT_API_KEY?: string;
  RIOT_VAL_BASE_URL?: string;
}

interface ScheduledEventLike {
  cron: string;
  scheduledTime: number;
}

interface ExecutionContextLike {
  waitUntil(promise: Promise<unknown>): void;
}

async function cleanupOldUsage(db: D1DatabaseBinding): Promise<void> {
  const cutoff = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  await db.prepare("DELETE FROM ai_usage_daily WHERE usage_date < ?").bind(cutoff).run();
}

const worker = {
  fetch: nextHandler.fetch,

  async scheduled(
    event: ScheduledEventLike,
    env: WorkerEnv,
    context: ExecutionContextLike,
  ): Promise<void> {
    if (!env.DB) {
      console.warn("Scheduled ranked-meta task skipped because the DB binding is unavailable");
      return;
    }

    const scheduledTime = Number.isFinite(event.scheduledTime) ? event.scheduledTime : Date.now();
    if (event.cron === "17 * * * *") {
      const apiKey = env.RIOT_API_KEY?.trim();
      const baseUrl = env.RIOT_VAL_BASE_URL?.trim();
      if (!apiKey || !baseUrl) {
        console.warn("Riot collection skipped because RIOT_API_KEY or RIOT_VAL_BASE_URL is missing");
        return;
      }
      const client = new RiotValorantApiClient({ apiKey, baseUrl });
      const result = await collectOptInMatches(env.DB, client, scheduledTime);
      console.log("Opt-in VALORANT match collection finished", result);
      return;
    }

    if (event.cron === "0 19 * * *") {
      const rebuild = rebuildLatestRecommendationSnapshots(env.DB, "jp", scheduledTime);
      context.waitUntil(cleanupOldUsage(env.DB));
      const result = await rebuild;
      console.log("Ranked meta recommendation snapshot rebuilt", result);
    }
  },
};

export default worker;

// Re-export OpenNext durable objects when the generated worker provides them.
// @ts-expect-error `.open-next/worker.js` is generated at build time.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
