/**
 * Fetches the playable Valorant agent roster from valorant-api.com,
 * downloads each agent's real portrait + role icon into `public/agents/<id>/`,
 * and generates the typed roster at `lib/agents.ts`.
 *
 * Run with: pnpm agents:sync   (alias for: tsx scripts/fetch-agents.ts)
 *
 * Phase 2 note: this same fetch can later upsert directly into D1 via Prisma
 * (no CSV pipeline). For now it produces a static, offline-safe roster.
 */
import { mkdir, writeFile, rm } from "node:fs/promises";
import path from "node:path";

const API = "https://valorant-api.com/v1/agents?isPlayableCharacter=true&language=en-US";
const ROLES = ["Duelist", "Initiator", "Controller", "Sentinel"] as const;
type Role = (typeof ROLES)[number];

const ROOT = process.cwd();
const PUBLIC_AGENTS = path.join(ROOT, "public", "agents");
const OUT_FILE = path.join(ROOT, "lib", "agents.ts");

type ApiAgent = {
  uuid: string;
  displayName: string;
  isPlayableCharacter: boolean;
  fullPortrait: string | null;
  displayIcon: string | null;
  backgroundGradientColors: string[];
  role: { displayName: string } | null;
};

/** "74321cff" -> "#74321c" (drop the alpha byte) */
function toHex(c: string): string {
  return `#${c.slice(0, 6)}`;
}

async function download(url: string, dest: string): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Download failed ${res.status}: ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buf);
}

async function main() {
  console.log("Fetching agents from valorant-api.com …");
  const res = await fetch(API);
  if (!res.ok) throw new Error(`API error ${res.status}`);
  const json = (await res.json()) as { data: ApiAgent[] };

  const agents = json.data
    .filter(
      (a) =>
        a.isPlayableCharacter &&
        a.role &&
        (ROLES as readonly string[]).includes(a.role.displayName) &&
        a.fullPortrait &&
        a.displayIcon,
    )
    .sort((a, b) => a.displayName.localeCompare(b.displayName));

  console.log(`Found ${agents.length} playable agents. Downloading images …`);

  // Clean + recreate the image output dir so removed agents don't linger.
  await rm(PUBLIC_AGENTS, { recursive: true, force: true });
  await mkdir(PUBLIC_AGENTS, { recursive: true });

  const records: string[] = [];
  for (const a of agents) {
    const dir = path.join(PUBLIC_AGENTS, a.uuid);
    await mkdir(dir, { recursive: true });
    await download(a.fullPortrait!, path.join(dir, "portrait.png"));
    await download(a.displayIcon!, path.join(dir, "icon.png"));

    const gradient = a.backgroundGradientColors.map(toHex);
    records.push(
      `  {\n` +
        `    id: ${JSON.stringify(a.uuid)},\n` +
        `    name: ${JSON.stringify(a.displayName)},\n` +
        `    role: ${JSON.stringify(a.role!.displayName as Role)},\n` +
        `    portrait: ${JSON.stringify(`/agents/${a.uuid}/portrait.png`)},\n` +
        `    icon: ${JSON.stringify(`/agents/${a.uuid}/icon.png`)},\n` +
        `    gradient: ${JSON.stringify(gradient)},\n` +
        `  }`,
    );
    process.stdout.write(`  ✓ ${a.displayName} (${a.role!.displayName})\n`);
  }

  const file =
    `// AUTO-GENERATED by scripts/fetch-agents.ts — do not edit by hand.\n` +
    `// Source: valorant-api.com (official Riot assets). Re-run: pnpm agents:sync\n` +
    `import type { Agent } from "./roles";\n\n` +
    `export const AGENTS: Agent[] = [\n${records.join(",\n")},\n];\n`;

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, file, "utf8");
  console.log(`\nWrote ${agents.length} agents to lib/agents.ts and images to public/agents/.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
